# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: LambdaGo

on:
  push:
    branches: [ "main" ]
    paths:
      - src/**
      - .github/workflows/lambdago.yml
      

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: ARCH=arm64 make build
      # run: go build -v ./...

    - name: Test
      run: make test
      #run: go test -v ./...

    - name: Zip
      run: make zip

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Upload Zip
      run: cd bin && aws lambda update-function-code --function-name GoHtmxStack-GetHandlerEF5E42BB-F7y5e4bDx6wz --zip-file fileb://bootstrap.zip
